all:main.c game.o list.o print.o

	gcc main.c game.o list.o print.o -o main -lm
	
game: game.c

	gcc game.c -c game.o -o
	
list: list.c

	gcc list.c -c list.o -o

print: print.c

	gcc print.c -c print.o -o


	



